apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "feelgood-gmbh-saas-chart.fullname" . }}-app
  labels:
    {{- include "feelgood-gmbh-saas-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "feelgood-gmbh-saas-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "feelgood-gmbh-saas-chart.name" . }}
    spec:
      initContainers:
        - name: schemagen-init
          image: {{ .Values.image.schemagen }} 
          command: ["/bin/sh", "-c", "echo 'Running schema migration for tenant...'; sleep 60"] 
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: db-url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.secretName }}
                  key: password
      containers:
        - name: nginx
          image: {{ .Values.image.nginx }}
          ports:
            - containerPort: {{ .Values.nginx.containerPort }}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
        - name: tomcat
          image: {{ .Values.image.tomcat }}
          ports:
            - containerPort: {{ .Values.tomcat.containerPort }}
        - name: artemis
          image: {{ .Values.image.artemis }}
          ports:
            - containerPort: {{ .Values.artemis.containerPort }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "feelgood-gmbh-saas-chart.fullname" . }}-nginx-config
