apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "feelgood-gmbh-saas-chart.fullname" . }}-app
  labels:
    {{- include "feelgood-gmbh-saas-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "feelgood-gmbh-saas-chart.fullname" . }}-app
                port:
                  number: {{ .Values.nginx.servicePort }}