apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "feelgood-gmbh-saas-chart.fullname" . }}-nginx-config
  labels:
    {{- include "feelgood-gmbh-saas-chart.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        auth_request /auth;
        proxy_pass http://tomcat:8080;
      }

      location = /auth {
        internal;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_pass http://keycloak:8080/auth/realms/{{ .Values.keycloak.realm }}/protocol/openid-connect/auth;
      }

      error_page 401 /401.html;
      location = /401.html {
        root /usr/share/nginx/html;
      }

      error_page 503 /maintenance.html;
      location = /maintenance.html {
        root /usr/share/nginx/html;
        internal;
      }
    }
