apiVersion: v1
kind: Secret
metadata:
  name: {{ include "feelgood-gmbh-saas-chart.fullname" . }}-secrets
  labels:
    {{- include "feelgood-gmbh-saas-chart.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ .Values.secrets.dbUsername | b64enc }}
  db-password: {{ .Values.secrets.dbPassword | b64enc }}
