apiVersion: v1
kind: Service
metadata:
  name: {{ include "feelgood-gmbh-saas-chart.fullname" . }}-app
  labels:
    {{- include "feelgood-gmbh-saas-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.nginx.servicePort }}
      targetPort: {{ .Values.nginx.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "feelgood-gmbh-saas-chart.name" . }}
